# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sam Drysdale
tagline:          'Game Programmer'
description:      'I make silly little games.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sam Drysdale'
  url:            https://www.linkedin.com/in/samueldrysdale/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/CommitToTheBit/committothebit.github.io

plugins:
- jekyll-paginate
- jekyll-gist
- redcarpet